spring:
  application:
    name: nexus
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    ignore-unsupported-db: true
    locations:
      - classpath:db/migration
logging:
  level:
    org.flywaydb.core: DEBUG
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900
  refresh-token-expiration: 604800
springdoc:
  use-generic-response: false
  override-with-generic-response: false